[package]
name = "earth"
version = "0.1.0"
authors = ["Gabriel Cardona <cgcardona@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
serde_derive = "1.0.102"
serde = "1.0.102"
clap = { features = ["yaml"] }
chain = { path = "chain" }
commands = { path = "commands" }
p2p = { path = "p2p" }
network = { path = "network" }
