[package]
name = "chain"
version = "0.1.0"
authors = ["Gabriel Cardona <cgcardona@gmail.com>"]
edition = "2018"

[dependencies]
rustc-hex = "2"
heapsize = "0.4"
rayon = "1.0"

[features]
default = []
test-helpers = []
