[package]
name = "bitcrypto"
version = "0.1.0"
authors = ["Gabriel Cardona <cgcardona@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "0.2.36"
siphasher = "0.1.1"
primitives = { path = "../primitives" }
